import turtle
t = turtle.Turtle()
b = turtle.Turtle()
c = turtle.Turtle()
ball = turtle.Turtle()
ball.shape("circle")
paddleSpeed = 20
ballSpeed = [3,4]
turtle.tracer(0,0)
t.ht()
b.ht()
c.ht()
ball.ht()
t.pu()
b.pu()
c.pu()
ball.pu()
def pong(x,y):
    ball.setpos(x,y)
    ball.pd()
    ball.clear()
    ball.color('white')
    ball.begin_fill()
    ball.circle(2)
    ball.end_fill()
    ball.pu()
def ballMove():
    pong(ball.xcor()+ballSpeed[0],ball.ycor()+ballSpeed[1])
    if ball.ycor() > 120 or ball.ycor() < -120:
        ballSpeed[1] = ballSpeed[1]*-1
def boundary():
    b.seth(0)
    b.setpos(0,-120)
    b.pd()
    b.color('black')
    b.begin_fill()
    b.fd(200)
    b.lt(90)
    b.fd(240)
    b.lt(90)
    b.fd(400)
    b.lt(90)
    b.fd(240)
    b.lt(90)
    b.fd(200)
    b.end_fill()
    b.pu()
def paddle(x,y):
    t.setpos(-200,y)
    t.color('white')
    t.seth(90)
    t.pd()
    t.begin_fill()
    t.fd(20)
    t.rt(90)
    t.fd(5)
    t.rt(90)
    t.fd(40)
    t.rt(90)
    t.fd(5)
    t.rt(90)
    t.fd(20)
    t.end_fill()
    t.pu()
def move(x,y):
    t.clear()
    paddle(x,y)
def down():
    t.clear()
    paddle(t.xcor(),t.ycor()-paddleSpeed)
    if t.ycor() > 100:
        t.setpos(t.xcor(),100)
        t.clear()
        paddle(t.xcor(),t.ycor())
    elif t.ycor() < -100:
        t.clear()
        t.setpos(t.xcor(),-100)
        paddle(t.xcor(),t.ycor())
    ballMove()
def up():
    t.clear()
    paddle(t.xcor(),t.ycor()+paddleSpeed)
    if t.ycor() > 100:
        t.setpos(t.xcor(),100)
        t.clear()
        paddle(t.xcor(),t.ycor())
    elif t.ycor() < -100:
        t.clear()
        t.setpos(t.xcor(),-100)
        paddle(t.xcor(),t.ycor())
    ballMove()
boundary()
paddle(0,0)
pong(0,0)
turtle.onkey(down,"Down")
turtle.onkey(up,"Up")
turtle.listen()
turtle.done()
